### ISSUE TITLE
Requirements incorrect & not numbered

### ISSUE THREAD

**Issue by jbrucker** [ReggieReo/ku-polls#1]
```
* Users can view a list of polls that are still open.
* Users can vote a list of polls that are still open.
  * Users might need to be logged in.
* A poll has to have start and end date.
* Users can view the result of each poll.
```
1. Requirements should be numbered list.
2. Should be at least 5 requirements.  Actually there are about 10.
3. Visitor can view list of polls, even after a poll is closed.
4. "might" incorrect. Either its a requirement or not.
5. "has to have start and end date" incorrect. Read the Vision.

**Comment by ReggieReo** [comment]
I fixed the requirements page, it would be great if you could review it. Thank you.
